### ISSUE TITLE
Multiple UnitID same connection parameters 

### ISSUE THREAD

**Issue by BurakOgutken** [cabbi/modbus_client_serial#5]
Hello, as you know, the RS485 port can be connected to more than one device, provided that the bound rate and parities are the same. You can connect to different unit IDs with a single connection. Is this possible with the library you wrote? I think the unit ID should be in the requests, not on the connection side.

**Comment by cabbi** [comment]
Each request can have its own unit id indeed.
Look to get read and write request methods: https://pub.dev/documentation/modbus_client/latest/modbus_client/ModbusElement/getReadRequest.html

**Comment by BurakOgutken** [comment]
So, should I remove the unit ID part from the code below?

```
  var modbusClient = ModbusClientSerialRtu(
      portName: "/dev/ttyS1",
      parity: SerialParity.even,
      unitId: 10,
      baudRate: SerialBaudRate.b9600);
```

**Comment by BurakOgutken** [comment]
Can you show me how to write it in the code here?

```
 var batteryStatus = ModbusEnumRegister(
        name: "BatteryStatus",
        address: 2,
        type: ModbusElementType.holdingRegister,
        enumValues: BatteryStatus.values,
        onUpdate: (self) {
          
        });

    var req = batteryStatus.getWriteRequest(BatteryStatus.running);
    await modbusClient.send(req);

    var batteryTemperature = ModbusInt16Register(
        name: "BatteryTemperature",
        type: ModbusElementType.holdingRegister,
        address: 2,
        onUpdate: (self) {
          if (kDebugMode) {
            print(self.value);
          }
        });

    await modbusClient.send(batteryTemperature.getReadRequest());

```

**Comment by cabbi** [comment]
Up to you, you can leave it. Unit id specified in the get request will override the connection one.

**Comment by BurakOgutken** [comment]
i found sorry for disturb
var req = batteryStatus.getWriteRequest(batteryStatus, unitId: 10);

**Comment by BurakOgutken** [comment]
sorry for disturb you :)

**Comment by BurakOgutken** [comment]
i am getting this error

```
E/flutter (22510): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [ModbusBitElement] Write request expects value to be 'ModbusIntEnum'!
E/flutter (22510): #0      ModbusEnumRegister._getRawValue (package:modbus_client/src/element_type/modbus_element_enum.dart:55:7)
E/flutter (22510): #1      ModbusElement.getWriteRequest (package:modbus_client/src/modbus_element.dart:72:48)
E/flutter (22510): #2      _MyHomePageState._incrementCounter (package:modbus/main.dart:84:29)
E/flutter (22510): #3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
E/flutter (22510): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
E/flutter (22510): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
E/flutter (22510): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
E/flutter (22510): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
E/flutter (22510): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:670:9)
E/flutter (22510): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
E/flutter (22510): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
E/flutter (22510): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
E/flutter (22510): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
E/flutter (22510): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
E/flutter (22510): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
E/flutter (22510): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
E/flutter (22510): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
E/flutter (22510): #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
E/flutter (22510): #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
E/flutter (22510): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
E/flutter (22510): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
E/flutter (22510): #21     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter (22510): #22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
E/flutter (22510): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
E/flutter (22510):
```

**Comment by BurakOgutken** [comment]
good job nice library thank you

**Comment by cabbi** [comment]
> WriteRequest(batteryStatus, unitId: 10);

Actually, in your case the value in the write request might be one of the values of BatteryStatus enum:
``` dart
var req = batteryStatus.getWriteRequest(BatteryStatus.running, unitId: 10);
```
